# Generated by Django 4.1.7 on 2023-04-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("alias", models.CharField(max_length=60)),
                (
                    "type",
                    models.CharField(
                        choices=[("cat", "Cat"), ("dog", "Dog")],
                        help_text="Type of animal",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
